const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const elements = new Map();
function element(key) {
  if (!elements.has(key)) elements.set(key, {innerHTML:'', textContent:'', value:'', dataset:{}, style:{}, classList:{add(){},remove(){}}, addEventListener(){}, querySelector(){return null}});
  return elements.get(key);
}
const storage = {getItem(){return null},setItem(){},removeItem(){}};
const messages = [];
const context = vm.createContext({console, Date, Math, Intl, JSON, structuredClone,
  localStorage:storage, sessionStorage:storage, setTimeout(){return 0}, clearTimeout(){}, setInterval(){return 0},
  navigator:{onLine:false,userAgent:'smoke-test'}, window:{addEventListener(){}},
  document:{addEventListener(){},querySelector:element,getElementById:element,querySelectorAll(){return []}},
  FormData:class {constructor(target){this.fields=target.fields}get(key){return this.fields[key]??null}},
  alert(message){messages.push(message)},confirm(){return false}});
const src = fs.readFileSync(require('node:path').join(__dirname,'app.js'),'utf8').replace(/\binitFirebaseCloud\(\);/,'');
vm.runInContext(src,context,{filename:'app.js'});
const run = (js) => vm.runInContext(js,context);
run(`user={role:'ADMIN',username:'admin',uid:'U1'};
db.projects=[
 {id:'P1',chantier:'Ambol',name:'Construction',budget:1000,start:'2026-01-01'},
 {id:'P2',chantier:'Autre',name:'Bâtiment',budget:300,start:'2026-01-01'},
 {id:'OLD',chantier:'Ancien',name:'Essai',budget:9999,deleted:true,start:'2026-01-01'}];
db.modules={purchases:[{id:'A1',project:'P1',designation:'Ciment',amount:150,date:'2026-01-10',paymentStatus:'Payé',fundSource:'Admin'}],cashEntries:[{id:'C1',project:'P1',amount:200,date:'2026-01-10'}],invoices:[],payroll:[],expenses:[],attendanceWeekly:[]};
db.expenses=[{id:'E1',project:'P1',amount:50,date:'2026-01-11',status:'Payée',fundSource:'Caisse Gestionnaire'},
{id:'E2',project:'P1',amount:300,date:'2026-01-11',status:'En attente'},
{id:'EOLD',project:'OLD',amount:5000,date:'2026-01-11',status:'Payée'}];
db.clientReceipts=[{id:'R1',project:'P1',client:'Client A',amount:700,date:'2026-01-12',status:'Validé'},
{id:'ROLD',project:'OLD',client:'Essai',amount:9000,date:'2026-01-12',status:'Validé'}];
db.quotes=[{id:'Q1',project:'P1',client:'Client A',date:'2026-01-01',status:'Accepté',sections:[{items:[{qty:1,pu:1000}]}]}];`);
const f = run(`financeScope()`);
run(`globalProjectContextBeforeTest=currentProjectContext;currentProjectContext=()=> 'P1';dashboardCore();`);
assert.match(element('#content').innerHTML,/NOMBRE DE CHANTIERS/);
assert.match(element('#content').innerHTML,/NOMBRE DE CHANTIERS[\s\S]{0,180}>2</);
run(`dashboardDetail('projects')`);
assert.match(element('#content').innerHTML,/Ambol/);
assert.match(element('#content').innerHTML,/Autre/);
assert.doesNotMatch(element('#content').innerHTML,/Ancien/);
run(`currentProjectContext=globalProjectContextBeforeTest`);
assert.equal(f.budget,1300);
assert.equal(f.actual,200);
assert.equal(f.cash,150);
assert.equal(f.treasury,350);
assert.equal(f.received,700);
assert.equal(f.contractRemaining,300);
assert.equal(run(`financeScope('P1').budgetRemaining`),800);
assert.equal(run(`canSpendManagerCash(151)`),false);
assert.equal(run(`canSpendManagerCash(150)`),true);
assert.match(run(`monthlyFinanceChart('revenue')`),/finance-chart-month/);
assert.match(run(`monthlyFinanceChart('expenses')`),/finance-chart-month/);
assert.match(run(`expenseCategoryChart()`),/finance-donut/);
assert.match(run(`reportsTable()`),/Chantier/);
assert.equal(run(`logicAuditIssues().some(x=>x.module==='Achats'&&x.ref==='A1')`),false);
run(`db.quotes.push({id:'Q2',project:'P1',client:'Client B',date:'2026-01-01',status:'Accepté',sections:[{items:[{qty:1,pu:500}]}]});
 db.quotes.push({id:'Q3',project:'P2',client:'Client A',date:'2026-01-01',status:'Accepté',sections:[{items:[{qty:1,pu:300}]}]});
 db.clientReceipts=[{id:'RA',project:'P1',client:'Client A',amount:250,date:'2026-01-12',status:'Validé'},
 {id:'RB',project:'P1',client:'Client B',amount:100,date:'2026-01-12',status:'Validé'},
 {id:'RC',project:'P2',client:'Client A',amount:30,date:'2026-01-12',status:'Validé'},
 {id:'RP',project:'P1',client:'Client A',amount:50,date:'2026-01-12',status:'En attente'}];`);
assert.equal(run(`clientPaymentRows('P1').find(x=>x.client==='Client A').percent`),25);
assert.equal(run(`clientPaymentRows('P1').find(x=>x.client==='Client A').remaining`),750);
assert.equal(run(`clientPaymentRows('P1').find(x=>x.client==='Client B').remaining`),400);
assert.equal(run(`clientPaymentRows('P2').find(x=>x.client==='Client A').remaining`),270);
run(`activeQuote=structuredClone(db.quotes[0]);activeQuote.object='Travaux';activeQuote.sections[0].items[0].pu=100;activeQuoteOriginalId='Q1';saveQuote();`);
assert.equal(run(`quoteFinancials(db.quotes[0]).ttc`),1000,'Accepted quote linked to receipt must remain unchanged');
run(`db.projects.push({id:'P3',chantier:'Nouveau',name:'Travaux',budget:0,start:'2026-01-01'});
 activeQuote={id:'DEV-NEGOCIE',project:'P3',client:'Client C',object:'Bâtiment',date:'2026-01-01',status:'Brouillon',discount:0,sections:[{items:[{qty:1,pu:100000000}]}]};
 activeQuoteOriginalId='';saveQuote();`);
assert.equal(run(`projectBudgetAmount(db.projects.find(p=>p.id==='P3'))`),0,'Brouillon is not a budget');
run(`activeQuote=structuredClone(db.quotes.find(q=>q.id==='DEV-NEGOCIE'));
 activeQuoteOriginalId='DEV-NEGOCIE';activeQuote.status='Accepté';activeQuote.discount=5000000;saveQuote();`);
assert.equal(run(`db.projects.find(p=>p.id==='P3').budget`),95000000,'Accepted quote, net of discount, becomes project budget');
assert.equal(run(`financeScope('P3').budget`),95000000);
assert.equal(run(`clientPaymentRows('P3').find(x=>x.client==='Client C').contract`),95000000);
run(`db.clientReceipts.push({id:'R3',project:'P3',client:'Client C',amount:20000000,date:'2026-01-12',status:'Validé'});
 activeQuote=structuredClone(db.quotes.find(q=>q.id==='DEV-NEGOCIE'));activeQuote.discount=6000000;saveQuote();`);
assert.equal(run(`db.projects.find(p=>p.id==='P3').budget`),94000000,'A negotiated amendment remains possible after partial payment');
assert.equal(run(`clientPaymentRows('P3').find(x=>x.client==='Client C').remaining`),74000000);
run(`activeQuote=structuredClone(db.quotes.find(q=>q.id==='DEV-NEGOCIE'));activeQuote.discount=85000000;saveQuote();`);
assert.equal(run(`db.projects.find(p=>p.id==='P3').budget`),94000000,'Cannot cut the contract below validated receipts');
run(`db.modules.invoices.push({id:'INV-3',project:'P3',client:'Client C',quoteId:'DEV-NEGOCIE',quoteAmount:94000000,trancheAmount:30000000,date:'2026-01-13'});
 activeQuote=structuredClone(db.quotes.find(q=>q.id==='DEV-NEGOCIE'));activeQuote.discount=7000000;saveQuote();`);
assert.equal(run(`db.projects.find(p=>p.id==='P3').budget`),94000000,'Issued invoice prevents rewriting quote total');
run(`db.projects.push({id:'P4',chantier:'Appartement',name:'Finition',budget:0,start:'2026-01-01'});
 db.quotes.push({id:'DEV-TRANCHE',project:'P4',client:'Client D',object:'Travaux de finition d’un bâtiment',date:'2026-01-01',status:'Accepté',discount:5000000,sections:[{title:'Lot 1',items:[{no:'1.1',designation:'Matériaux',unit:'ens',qty:1,pu:60000000},{no:'1.2',designation:'Pose',unit:'jour',qty:2,pu:20000000}]}]});
 invoicesPage=()=>{};invoiceForm('','P4');`);
assert.match(element('#content').innerHTML,/Matériaux/);
assert.match(element('#content').innerHTML,/Pose/);
assert.match(element('#content').innerHTML,/Travaux de finition d’un bâtiment/);
assert.match(element('#content').innerHTML,/95000000/);
const form=element('#fInvoice');
form.fields={recordId:'INV-TRANCHE',invoiceNo:'FAC-TEST-1',date:'2026-01-14',project:'P4',quoteId:'DEV-TRANCHE',client:'Client D',billingClientName:'Entreprise Client D',invoiceDesignation:'Première tranche sur paiement des travaux de finition d’un bâtiment',quoteAmount:'95000000',trancheAmount:'45000000',tranchePercent:'47.37',note:'Facture personnalisée'};
const originalInvoiceFields={...form.fields};
form.onsubmit({preventDefault(){},target:form});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').trancheAmount`),45000000);
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').invoiceDesignation`),'Première tranche sur paiement des travaux de finition d’un bâtiment');
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').client`),'Client D','Accounting client stays linked to the quote');
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').billingClientName`),'Entreprise Client D');
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').quoteLines.length`),2);
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').quoteLines[1].qty`),2);
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').quoteLines[1].pu`),20000000);
assert.equal(run(`invoicePaidForProject('P4','','Client D','DEV-TRANCHE')`),45000000);
assert.equal(run(`projectFinancialSnapshot('P4').toInvoice`),50000000);
assert.equal(run(`clientPaymentRows('P4')[0].remaining`),95000000,'Invoice issuance alone does not constitute payment');
run(`db.clientReceipts.push({id:'R4',project:'P4',client:'Client D',amount:20000000,date:'2026-01-15',status:'Validé'});`);
assert.equal(run(`clientPaymentRows('P4')[0].remaining`),75000000);
assert.equal(run(`projectFinancialSnapshot('P4').receivable`),25000000);
run(`invoiceDetail('INV-TRANCHE')`);
assert.match(element('#content').innerHTML,/Première tranche sur paiement des travaux de finition d’un bâtiment/);
assert.match(element('#content').innerHTML,/Entreprise Client D/);
assert.doesNotMatch(element('#content').innerHTML,/Matériaux|Pose/,'Technical quote lines are absent from the invoice view');
assert.match(element('#content').innerHTML,/45[^<]*000[^<]*000/);
run(`db.projects.push({id:'P5',chantier:'Attachement',name:'Maçonnerie',budget:0,start:'2026-01-01'});
 db.quotes.push({id:'DEV-MESURE',project:'P5',client:'Client E',object:'Mur',date:'2026-01-01',status:'Accepté',discount:10000000,sections:[{title:'Gros œuvre',items:[{no:'1.1',designation:'Murs',unit:'ens',qty:2,pu:50000000}]}]});
 invoiceForm('','P5');`);
const attachment=element('#fInvoice');
attachment.fields={recordId:'INV-MESURE-1',invoiceNo:'FAC-MESURE-1',date:'2026-01-14',project:'P5',quoteId:'DEV-MESURE',client:'Client E',quoteAmount:'90000000',trancheAmount:'0',invoiceType:'Attachement',billedQty_0:'1',note:''};
attachment.onsubmit({preventDefault(){},target:attachment});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-MESURE-1').trancheAmount`),45000000);
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-MESURE-1').billedLines[0].billedQty`),1);
assert.equal(run(`projectFinancialSnapshot('P5').toInvoice`),45000000);
attachment.fields={...attachment.fields,recordId:'INV-MESURE-2',invoiceNo:'FAC-MESURE-2',billedQty_0:'2'};
attachment.onsubmit({preventDefault(){},target:attachment});
assert.equal(run(`invoiceRows().some(i=>i.id==='INV-MESURE-2')`),false,'Already billed quantities cannot be invoiced again');
assert.ok(messages.some(m=>String(m).includes('quantité facturée dépasse')));
run(`activeQuote=structuredClone(db.quotes.find(q=>q.id==='DEV-MESURE'));activeQuoteOriginalId='DEV-MESURE';activeQuote.sections[0].items[0].designation='Autres murs';saveQuote();`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-MESURE').sections[0].items[0].designation`),'Murs','Quote lines of an issued invoice remain fixed');
run(`db.clientReceipts.push({id:'R4-LINKED',project:'P4',client:'Client D',invoiceId:'INV-TRANCHE',amount:10000000,date:'2026-01-16',status:'Validé'});invoiceDetail('INV-TRANCHE');`);
assert.equal(run(`invoiceReceiptPaid('INV-TRANCHE')`),10000000);
assert.equal(run(`clientPaymentRows('P4')[0].remaining`),65000000);
assert.match(element('#content').innerHTML,/Encaissé et attribué à cette facture/);
run(`invoiceForm('INV-TRANCHE')`);
form.fields={...originalInvoiceFields,invoiceDesignation:'Deuxième formulation de la première tranche',billingClientName:'Client D SARL',date:'2026-01-17'};
form.onsubmit({preventDefault(){},target:form});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').invoiceDesignation`),'Deuxième formulation de la première tranche',messages.join(' | '));
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').billingClientName`),'Client D SARL');
assert.equal(run(`clientPaymentRows('P4')[0].remaining`),65000000,'Invoice wording edit cannot alter the client debt');
form.fields={...form.fields,trancheAmount:'40000000'};
form.onsubmit({preventDefault(){},target:form});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').trancheAmount`),40000000,'Amount can be corrected without breaking validated receipts');
assert.equal(run(`clientPaymentRows('P4')[0].remaining`),65000000);
form.fields={...form.fields,trancheAmount:'9000000'};
form.onsubmit({preventDefault(){},target:form});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-TRANCHE').trancheAmount`),40000000,'Cannot lower invoice below validated linked payment');
assert.ok(messages.some(m=>String(m).includes('encaissements validés sont déjà liés')));
assert.ok(!messages.some(m=>String(m).includes('Cette tranche dépasse')));
console.log('PASS: devis 100M−5M=95M, facture 45M exacte, attachement qty 1/2 =45M, quantités non doublées, reste client distinct des factures.');
run(`db.quotes.push({id:'DEV-CARRELAGE',project:'P4',client:'Client D',object:'Pose de carrelage',date:'2026-01-20',status:'Brouillon',sections:[{items:[{designation:'Carrelage',unit:'m²',qty:100,pu:130000}]}]});`);
assert.equal(run(`quoteFinancials(db.quotes.find(q=>q.id==='DEV-CARRELAGE')).ttc`),13000000);
assert.equal(run(`forecastRequired(forecastLines(db.quotes.find(q=>q.id==='DEV-CARRELAGE'))[0],generateMaterialForecast(db.quotes.find(q=>q.id==='DEV-CARRELAGE')).materials[0])`),310);
assert.equal(run(`forecastRequired(forecastLines(db.quotes.find(q=>q.id==='DEV-CARRELAGE'))[0],generateMaterialForecast(db.quotes.find(q=>q.id==='DEV-CARRELAGE')).materials[1])`),22);
run(`materialPlanPage('DEV-CARRELAGE')`);
assert.match(element('#content').innerHTML,/310 pièces/);
assert.match(element('#content').innerHTML,/Coupe-carreaux/);
assert.match(element('#content').innerHTML,/PLANNING GANTT/);
assert.match(element('#content').innerHTML,/Carrelage/);
run(`editForecastMaterial(1,'coefficient','10');editForecastMaterial(1,'loss','0');saveMaterialForecast();`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-CARRELAGE').materialForecast.materials[1].coefficient`),10);
assert.equal(run(`quoteFinancials(db.quotes.find(q=>q.id==='DEV-CARRELAGE')).ttc`),13000000,'Material calculations cannot change client quote');
assert.equal(run(`forecastRequired(forecastLines(db.quotes.find(q=>q.id==='DEV-CARRELAGE'))[0],db.quotes.find(q=>q.id==='DEV-CARRELAGE').materialForecast.materials[1])`),40,'Manual dosage can yield 40 bags');
run(`db.quotes.find(q=>q.id==='DEV-CARRELAGE').sections[0].items[0].qty=101;materialPlanPage('DEV-CARRELAGE');`);
assert.match(element('#content').innerHTML,/Le devis a changé/);
run(`user={role:'TECHNICIEN',username:'tech',uid:'U2'};materialPlanPage('DEV-CARRELAGE')`);
assert.doesNotMatch(element('#content').innerHTML,/13000000|130 000|Enregistrer le plan/,'Site crew sees quantities, not client prices');
run(`saveMaterialForecast()`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-CARRELAGE').materialForecast.materials[1].coefficient`),10,'Only Admin may save the forecast');
console.log('PASS: plan matériel séparé, carrelage 310 pièces, colle 22 sacs indicatifs, dosage modifiable, édition Admin, devis inchangé.');
run(`user={role:'ADMIN',username:'admin',uid:'U1'};
 db.projects.push({id:'P-GANTT',chantier:'Site Gantt',name:'Finition',start:'2026-10-01',end:'2026-10-12'});
 db.quotes.push({id:'DEV-GANTT',project:'P-GANTT',client:'Client F',object:'Finitions',date:'2026-09-25',status:'Brouillon',sections:[{title:'Lot sols',items:[{designation:'Pose de carrelage',qty:100,unit:'m²',pu:130000},{designation:'Jointement',qty:0,unit:'m²',pu:0}]},{title:'Lot peinture',items:[{designation:'Peinture des murs',qty:50,unit:'m²',pu:30000}]}]});`);
assert.equal(run(`generateForecastGantt(db.quotes.find(q=>q.id==='DEV-GANTT')).tasks.length`),3,'Even a designation with zero quantity appears in Gantt');
assert.equal(run(`generateForecastGantt(db.quotes.find(q=>q.id==='DEV-GANTT')).tasks[0].start`),'2026-10-01');
assert.equal(run(`generateForecastGantt(db.quotes.find(q=>q.id==='DEV-GANTT')).tasks[2].end`),'2026-10-12');
run(`materialPlanPage('DEV-GANTT')`);
assert.match(element('#content').innerHTML,/Jointement/);
assert.match(element('#content').innerHTML,/2026-10-12/);
run(`editForecastGantt(0,'end','2026-10-03');editForecastGantt(0,'progress','50');saveMaterialForecast()`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-GANTT').materialForecast.gantt.tasks[0].end`),'2026-10-03');
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-GANTT').materialForecast.gantt.tasks[0].progress`),50);
assert.equal(run(`quoteFinancials(db.quotes.find(q=>q.id==='DEV-GANTT')).ttc`),14500000);
run(`editForecastGantt(0,'end','2026-09-30')`);
assert.equal(run(`activeMaterialForecast.gantt.tasks[0].end`),'2026-10-03','Invalid date must not replace valid plan');
run(`user={role:'TECHNICIEN',username:'tech',uid:'U2'};materialPlanPage('DEV-GANTT');editForecastGantt(0,'progress','100')`);
assert.equal(run(`activeMaterialForecast.gantt.tasks[0].progress`),50,'Crew cannot edit Gantt');
assert.doesNotMatch(element('#content').innerHTML,/130000|30000|14500000/,'Gantt and material preview contain no quote prices');
console.log('PASS: Gantt des désignations, dates chantier, ajustement et avancement conservés, lecture seule équipe.');
run(`user={role:'ADMIN',username:'admin',uid:'U1'};
 db.quotes.push({id:'DEV-CONSTRUCTION',project:'P-GANTT',client:'Client F',object:'Construction générale de bâtiment',date:'2026-09-25',status:'Brouillon',sections:[{title:'Préparation',items:[{designation:'Installation chantier',unit:'forfait',qty:1,pu:1000000},{designation:'Terrassement',unit:'m³',qty:40,pu:20000}]},{title:'Second œuvre',items:[{designation:'Installation électrique',unit:'ens',qty:0,pu:0},{designation:'Peinture des murs',unit:'m²',qty:60,pu:30000},{designation:'Poste spécifique non répertorié',unit:'ens',qty:1,pu:1000}]}]});`);
const complex=run(`generateMaterialForecast(db.quotes.find(q=>q.id==='DEV-CONSTRUCTION'))`);
assert.equal(complex.gantt.tasks.length,5,'Gantt carries all written designations');
assert.equal(new Set(complex.materials.map(m=>m.lineKey)).size,5,'Each designation has a material line');
assert.equal(new Set(complex.tools.map(t=>t.lineKey)).size,5,'Each designation has a tool line');
assert.ok(complex.materials.some(m=>m.lineKey==='0:0'&&m.name.includes('Clôture')));
assert.ok(complex.materials.some(m=>m.lineKey==='1:0'&&m.name.includes('Câbles')));
assert.ok(complex.materials.some(m=>m.lineKey==='1:2'&&m.name.includes('à préciser')));
assert.equal(run(`forecastRequired(forecastLines(db.quotes.find(q=>q.id==='DEV-CONSTRUCTION'))[2],generateMaterialForecast(db.quotes.find(q=>q.id==='DEV-CONSTRUCTION')).materials.find(m=>m.lineKey==='1:0'))`),null,'Zero-quantity electrical work is marked to price, not omitted');
const quoteBefore=run(`quoteFinancials(db.quotes.find(q=>q.id==='DEV-CONSTRUCTION')).ttc`);
run(`materialPlanPage('DEV-CONSTRUCTION');editForecastMaterial(0,'manualQuantity','12');editForecastMaterial(0,'unit','mètres');editForecastGantt(0,'name','Installation et signalisation du chantier');saveMaterialForecast();`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.materials[0].manualQuantity`),12);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.gantt.tasks[0].name`),'Installation et signalisation du chantier');
assert.equal(run(`quoteFinancials(db.quotes.find(q=>q.id==='DEV-CONSTRUCTION')).ttc`),quoteBefore,'Internal adjustments leave client quote intact');
assert.match(element('#content').innerHTML,/DEVIS INTERNE — MATÉRIAUX PAR DÉSIGNATION/);
assert.match(element('#content').innerHTML,/Installation électrique/);
assert.match(element('#content').innerHTML,/À chiffrer/);
run(`db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.schemaVersion=1;
 db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.materials=db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.materials.filter(m=>m.lineKey==='0:0');
 db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.tools=db.quotes.find(q=>q.id==='DEV-CONSTRUCTION').materialForecast.tools.filter(t=>t.lineKey==='0:0');
 materialPlanPage('DEV-CONSTRUCTION');`);
assert.equal(run(`new Set(activeMaterialForecast.materials.map(m=>m.lineKey)).size`),5,'Older partial forecast fills omitted designations without replacing existing work');
assert.equal(run(`activeMaterialForecast.materials.find(m=>m.lineKey==='0:0').manualQuantity`),12,'Older custom quantity survives upgrade');
console.log('PASS: construction générale, désignations complètes, lots sans métrés à chiffrer, prévision et Gantt éditables sans affecter le devis client.');
run(`user={role:'ADMIN',username:'admin',uid:'U1'};
 db.projects.push({id:'P-REST',chantier:'Récupération',name:'Test',start:'2026-09-01',budget:100,deleted:true,deletedAt:'2026-09-20T00:00:00Z'});
 db.quotes.push({id:'DEV-REST',project:'P-REST',client:'Client test',object:'Travaux',status:'Accepté',deleted:true,deletedAt:'2026-09-21T00:00:00Z',sections:[{items:[{designation:'Travaux',qty:1,pu:500}]}]});
 db.modules.invoices.push({id:'INV-REST',project:'P-REST',quoteId:'DEV-REST',client:'Client test',trancheAmount:200,deleted:true,deletedAt:'2026-09-22T00:00:00Z'});
 db.clientReceipts.push({id:'REC-REST',project:'P-REST',invoiceId:'INV-REST',client:'Client test',amount:100,status:'Validé',deleted:true,deletedAt:'2026-09-23T00:00:00Z'});
 db.expenses.push({id:'DEP-REST',project:'P-REST',label:'Transport',amount:50,status:'Payée',deleted:true,deletedAt:'2026-09-24T00:00:00Z'});
 db.modules.purchases.push({id:'ACH-REST',project:'P-REST',designation:'Outils',amount:40,deleted:true,deletedAt:'2026-09-24T00:00:00Z'});
 trashPage();`);
for(const id of ['P-REST','DEV-REST','INV-REST','REC-REST','DEP-REST','ACH-REST'])assert.match(element('#content').innerHTML,new RegExp(id));
run(`restoreGeneric('invoices','INV-REST')`);
assert.equal(run(`db.modules.invoices.find(x=>x.id==='INV-REST').deleted`),true,'Cannot restore invoice while quote and project are deleted');
run(`restoreRecord('projects','projects','P-REST');restoreRecord('quotes','quotes','DEV-REST')`);
assert.equal(run(`db.projects.find(x=>x.id==='P-REST').budget`),500,'Restored accepted quote updates the chantier budget');
run(`restoreGeneric('invoices','INV-REST');restoreRecord('clientReceipts','clientReceipts','REC-REST');restoreRecord('expenses','expenses','DEP-REST');restoreGeneric('purchases','ACH-REST')`);
assert.equal(run(`db.clientReceipts.find(x=>x.id==='REC-REST').deleted`),false);
assert.equal(run(`db.expenses.find(x=>x.id==='DEP-REST').deleted`),false);
assert.equal(run(`db.modules.purchases.find(x=>x.id==='ACH-REST').deleted`),false);
assert.equal(run(`projectFinancialSnapshot('P-REST').received`),100);
assert.equal(run(`projectFinancialSnapshot('P-REST').actual`),50,'Restored expense is included in finance once');
run(`trashPage()`);
assert.doesNotMatch(element('#content').innerHTML,/REC-REST|DEV-REST|ACH-REST/,'Recovered items leave the bin');
console.log('PASS: corbeille couvre devis, factures, paiements, dépenses et achats ; restauration dans l’ordre des dépendances, budget recalculé.');
// A direct budget is an explicit source and cannot be replaced by a validated quote.
run(`user={role:'ADMIN',username:'admin',uid:'U1'};cloudReady=false;
db.projects.push({id:'P-MAN',chantier:'Direct',name:'Construction',client:'Direct Client',budget:95000000,budgetSource:'manuel',createdAt:'2026-01-01T00:00:00Z'});
db.quotes.push({id:'Q-MAN',project:'P-MAN',client:'Direct Client',status:'Accepté',sections:[{items:[{qty:1,pu:110000000}]}]});
syncProjectQuoteBudget('P-MAN');`);
assert.equal(run(`projectBudgetAmount(db.projects.find(p=>p.id==='P-MAN'))`),95000000);
assert.equal(run(`clientContractAmount('P-MAN','Direct Client')`),95000000);
assert.equal(run(`clientPaymentRows('P-MAN')[0].remaining`),95000000);
run(`invoiceForm('','P-MAN')`);
assert.match(element('#content').innerHTML,/value="95000000"/,'Direct budget prefills the invoice contract');
assert.equal(run(`db.projects.find(p=>p.id==='P-MAN').budgetSource`),'manuel');
element('#fInvoice').fields={recordId:'INV-MAN',invoiceNo:'FAC-2026-0999',date:'2026-09-25',project:'P-MAN',quoteId:'',client:'Direct Client',billingClientName:'Direct Client',invoiceDesignation:'Première tranche',quoteAmount:'95000000',invoiceType:'Tranche',trancheAmount:'45000000',note:''};
element('#fInvoice').onsubmit({preventDefault(){},target:element('#fInvoice')});
assert.equal(run(`invoiceRows().find(i=>i.id==='INV-MAN').trancheAmount`),45000000);
assert.equal(run(`projectFinancialSnapshot('P-MAN').toInvoice`),50000000);
run(`db.clientReceipts.push({id:'PAY-MAN',project:'P-MAN',client:'Direct Client',amount:20000000,date:'2026-09-25',status:'Validé'})`);
assert.equal(run(`clientPaymentRows('P-MAN')[0].remaining`),75000000);
run(`projectForm()`);
assert.match(element('#content').innerHTML,/Depuis devis validé/);
assert.match(element('#content').innerHTML,/Saisie directe sans devis/);
element('#fProject').fields={chantier:'New Manual Site',name:'New Work',client:'Direct Client',budgetSource:'manuel',budget:'80000000',start:'2026-10-01',end:'2026-12-01',progress:'0',status:'Prévu'};
element('#fProject').onsubmit({preventDefault(){},target:element('#fProject')});
assert.equal(run(`db.projects.find(p=>p.chantier==='New Manual Site').budget`),80000000);
assert.equal(run(`db.projects.find(p=>p.chantier==='New Manual Site').budgetSource`),'manuel');
run(`db.projects.find(p=>p.id==='P-MAN').budgetSource='devis';syncProjectQuoteBudget('P-MAN')`);
assert.equal(run(`projectBudgetAmount(db.projects.find(p=>p.id==='P-MAN'))`),110000000);
console.log('PASS: budget manuel et devis au choix, client/contrat et facture manuelle, conversion explicite.');
// A devis selects the registered client and cannot quietly attach a different chantier's client.
run(`user={role:'ADMIN',username:'admin',uid:'U1'};cloudReady=false;
db.modules.clients.push({id:'CLI-Z',values:['Mr Zahim','034 12 345 67','Antsirabe']},{id:'CLI-H',values:['Mme Hery','032 98 765 43','Tana']});
db.projects.push({id:'P-Z',chantier:'HOMEOPHARMA',name:'Finition',client:'Mr Zahim',budgetSource:'devis'},{id:'P-H',chantier:'AUTRE',name:'Travaux',client:'Mme Hery',budgetSource:'devis'});
activeQuote=newQuote();activeQuote.id='DEV-SELECT-CLIENT';activeQuote.project='P-Z';activeQuote.object='Finition bâtiment';activeQuote.sections[0].items[0].pu=1000;activeQuoteOriginalId='';renderQuoteEditor();`);
assert.match(element('#content').innerHTML,/id="quoteClientSelect"/);
assert.match(element('#content').innerHTML,/value="CLI-Z" selected/);
assert.equal(run(`activeQuote.clientId`),'CLI-Z');
assert.equal(run(`activeQuote.clientPhone`),'034 12 345 67');
run(`quoteChooseClient('CLI-H');saveQuote()`);
assert.match(messages.at(-1),/ne correspond pas au client de ce chantier/);
assert.equal(run(`db.quotes.some(q=>q.id==='DEV-SELECT-CLIENT')`),false);
run(`quoteChooseProject('P-H');saveQuote()`);
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-SELECT-CLIENT').clientId`),'CLI-H');
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-SELECT-CLIENT').client`),'Mme Hery');
assert.equal(run(`db.quotes.find(q=>q.id==='DEV-SELECT-CLIENT').clientAddress`),'Tana');
console.log('PASS: client du devis choisi dans CLIENTS, prérempli depuis le chantier, cohérence et identité enregistrée.');
run(`quoteEditor('DEV-SELECT-CLIENT')`);
assert.match(element('#content').innerHTML,/onclick="printA4AutoFit\(\)"[^>]*>🖨 Imprimer/);
assert.match(element('#content').innerHTML,/onclick="exportQuotePdf\(\)"[^>]*>⬇ Exporter PDF/);
let printCount=0;
context.window.print=()=>{printCount++};
context.document.documentElement={classList:{add(){},remove(){}}};
run(`exportQuotePdf()`);
assert.equal(printCount,1);
assert.match(messages.at(-1),/Enregistrer au format PDF/);
console.log('PASS: devis avec deux actions distinctes Imprimer et Exporter PDF via la sortie PDF du navigateur.');
run(`db.projects.push({id:'P-Z2',chantier:'CHANTIER Z 2',name:'Installation',client:'Mr Zahim'});
db.projects.push({id:'P-Z-OLD',chantier:'CHANTIER Z SUPPRIMÉ',client:'Mr Zahim',deleted:true});
globalProjectContextBeforeTest=currentProjectContext;currentProjectContext=()=> 'P-H';
clientProjectsPage('CLI-Z');`);
assert.match(element('#content').innerHTML,/HOMEOPHARMA/);
assert.match(element('#content').innerHTML,/CHANTIER Z 2/);
assert.doesNotMatch(element('#content').innerHTML,/CHANTIER Z SUPPRIMÉ/);
assert.doesNotMatch(element('#content').innerHTML,/AUTRE/);
run(`projectClientDetail('P-Z')`);
assert.match(element('#content').innerHTML,/Client :/);
assert.match(element('#content').innerHTML,/Mr Zahim/);
run(`sessionStorageGetBeforeTest=sessionStorage.getItem;sessionStorage.getItem=()=> '1';generic('clients')`);
assert.match(element('#content').innerHTML,/clientProjectsPage\(decodeURIComponent\(this.dataset.id\)\)/);
assert.match(element('#content').innerHTML,/Mr Zahim/);
run(`sessionStorage.getItem=sessionStorageGetBeforeTest;currentProjectContext=globalProjectContextBeforeTest`);
console.log('PASS: chantier cliquable vers client, client cliquable vers tous ses chantiers actifs, indépendamment du filtre.');
// 24-hour corrections must preserve the posted ledger until the Admin decides.
run(`cloudReady=false;user={role:'GESTIONNAIRE',username:'manager',uid:'M1'};
db.editRequests=[];
db.expenses.push({id:'EDIT-24',project:'P1',owner:'manager',createdAt:new Date(Date.now()-25*60*60*1000).toISOString(),updatedAt:'v1',amount:25,status:'Payée',fundSource:'Admin',label:'Avant'});
db.expenses.push({id:'EDIT-23',project:'P1',owner:'manager',createdAt:new Date(Date.now()-23*60*60*1000).toISOString(),updatedAt:'v1',amount:12,status:'En attente',fundSource:'Admin'});`);
assert.equal(run(`canUserChange(db.expenses.find(x=>x.id==='EDIT-23'))`),true);
assert.equal(run(`canUserChange(db.expenses.find(x=>x.id==='EDIT-24'))`),false);
assert.equal(run(`requestEditIfRequired('expenses',db.expenses.find(x=>x.id==='EDIT-23'),{amount:15})`),false);
assert.equal(run(`requestEditIfRequired('expenses',db.expenses.find(x=>x.id==='EDIT-24'),{amount:30})`),true);
assert.equal(run(`db.expenses.find(x=>x.id==='EDIT-24').amount`),25,'Unapproved draft cannot affect ledger');
assert.equal(run(`db.editRequests[0].status`),'En attente');
run(`user={role:'ADMIN',username:'admin',uid:'U1'};decideEditRequest(db.editRequests[0].id,true)`);
assert.equal(run(`db.expenses.find(x=>x.id==='EDIT-24').amount`),30);
assert.equal(run(`db.editRequests[0].status`),'Validée');
run(`user={role:'GESTIONNAIRE',username:'manager',uid:'M1'};
requestEditIfRequired('expenses',db.expenses.find(x=>x.id==='EDIT-24'),{amount:40});`);
run(`db.expenses.find(x=>x.id==='EDIT-24').updatedAt='later';user={role:'ADMIN',username:'admin',uid:'U1'};decideEditRequest(db.editRequests[1].id,true)`);
assert.equal(run(`db.expenses.find(x=>x.id==='EDIT-24').amount`),30,'Stale request must not overwrite later edits');
run(`decideEditRequest(db.editRequests[1].id,false)`);
assert.equal(run(`db.editRequests[1].status`),'Refusée');
run(`user={role:'GESTIONNAIRE',username:'stranger',uid:'M2'}`);
assert.equal(run(`requestEditIfRequired('expenses',db.expenses.find(x=>x.id==='EDIT-24'),{amount:1000})`),true);
assert.equal(run(`db.editRequests.length`),2,'Another owner cannot create a correction');
console.log('PASS: édition directe <24 h, demande après 24 h, acceptation/refus Admin, conflit et propriété.');
run(`user={role:'ADMIN',username:'admin',uid:'U1'}`);
(async()=>{
 const cloudWrites=[];
 context.navigator.onLine=true;
 context.mockCloudStore={collection(name){return {doc(id){return {async set(payload){cloudWrites.push({name,id,payload})}}}}}};
 run(`cloudReady=true;fbStore=mockCloudStore;
 db.expenses.push({id:'DEP-CLOUD-REST',project:'P1',label:'Essai Cloud',amount:12,deleted:true,deletedAt:'2026-09-24T00:00:00Z'})`);
 await run(`restoreRecord('expenses','expenses','DEP-CLOUD-REST')`);
 const expenseWrite=cloudWrites.find(w=>w.name==='expenses'&&w.id==='DEP-CLOUD-REST');
 assert.ok(expenseWrite,'Cloud receives the restored expense');
 assert.equal(expenseWrite.payload.deleted,false,'Cloud receives the restored record');
 context.mockCloudStore={collection(){return {doc(){return {async set(){throw Error('Accès refusé')}}}}}};
 run(`fbStore=mockCloudStore;
 db.expenses.push({id:'DEP-CLOUD-FAIL',project:'P1',label:'Échec Cloud',amount:12,deleted:true,deletedAt:'2026-09-24T00:00:00Z'})`);
 const previousError=console.error;console.error=()=>{};
 try{await run(`restoreRecord('expenses','expenses','DEP-CLOUD-FAIL')`)}finally{console.error=previousError}
 assert.equal(run(`db.expenses.find(x=>x.id==='DEP-CLOUD-FAIL').deleted`),true,'Denied Cloud write leaves the record in the bin');
 console.log('PASS: restauration Cloud expédiée, refus Cloud sans faux succès local.');
})().catch(e=>{console.error(e);process.exitCode=1});
