const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync(__dirname+'/app.js','utf8');
const start=code.indexOf('function quoteDraftStorageKey(){');
const end=code.indexOf('function quoteEditor(id=""){',start);
const goStart=code.indexOf('const unsavedModuleViews=new Map();');
const goEnd=code.indexOf('\nfunction printCurrentView()',goStart);
assert(start>0&&end>start&&goStart>0&&goEnd>goStart);
const store=new Map(),localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
const quote={id:'DEV-1',date:'2026-09-29',validUntil:'',object:'',sections:[{title:'Lot',items:[{no:'1.1',designation:'',unit:'m²',qty:1,pu:0}]}]};
const field=value=>({value:String(value)});
const row={classList:{contains:c=>false},querySelectorAll:()=>[field('1.1'),field('Carrelage posé'),field('m²'),field('100'),field('130000')]};
const section={classList:{contains:c=>c==='quote-section-row'},querySelector:()=>field('Finition')};
const editor={querySelector(sel){return ({'.quote-head':{querySelector:s=>field(s==='.quote-no input'?'DEV-1':'2026-09-29')},'.quote-meta':{querySelector:()=>field('2026-10-29')},'.quote-object input':field('Travaux de finition')})[sel]||null},querySelectorAll:()=>[section,row]};
const content={nodes:[{editing:true}],querySelector:sel=>sel.includes('.quote-editor')?editor:content.nodes.some(n=>n.editing)?{}:null,get firstChild(){return this.nodes[0]},replaceChildren(f){this.nodes=f.nodes.splice(0)}};
const menu=[{dataset:{page:'quotes'},classList:{toggle(){}}},{dataset:{page:'clients'},classList:{toggle(){}}}];
const document={querySelector:sel=>sel==='#content .quote-editor'?editor:null,addEventListener(){},activeElement:{closest(){return null}},getElementById:id=>id==='content'?content:null,querySelectorAll:()=>menu,createDocumentFragment:()=>({nodes:[],appendChild(n){content.nodes.shift();this.nodes.push(n)}})};
const ctx=vm.createContext({document,localStorage,user:{role:'ADMIN',uid:'u1'},cloudCurrentPage:'quotes',activeQuote:quote,activeQuoteOriginalId:'',console,renderGlobalProjectSelector(){},originalGo(page){ctx.cloudCurrentPage=page;content.nodes=[{editing:false,page}]}});
vm.runInContext(code.slice(start,end)+code.slice(goStart,goEnd),ctx);
vm.runInContext("go('clients')",ctx);
const d=JSON.parse(store.get('nysoa_quote_draft_v2_u1'));
assert.equal(d.quote.object,'Travaux de finition');
assert.equal(d.quote.sections[0].items[0].designation,'Carrelage posé');
assert.equal(d.quote.sections[0].items[0].qty,100);
assert.equal(d.quote.sections[0].items[0].pu,130000);
vm.runInContext("go('quotes')",ctx);
assert.equal(content.nodes[0].editing,true);
vm.runInContext('clearQuoteDraft()',ctx);
assert.equal(store.size,0);
console.log('PASS: saisie et valeurs du devis conservées après changement de module ; brouillon effacé après enregistrement.');
