const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const code=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
const start=code.indexOf('const unsavedModuleViews=new Map();');
const end=code.indexOf('\nfunction printCurrentView()',start);
assert(start>0&&end>start,'Gestion des brouillons introuvable');
const content={nodes:[],querySelector(selector){return this.nodes.some(n=>n.editing)?{}:null},get firstChild(){return this.nodes[0]},replaceChildren(fragment){this.nodes=fragment.nodes.splice(0)}};
const menu=[{dataset:{page:'quotes'},classList:{toggle(){}}},{dataset:{page:'clients'},classList:{toggle(){}}}];
const document={activeElement:{closest(){return null}},getElementById(id){return id==='content'?content:null},querySelectorAll(){return menu},createDocumentFragment(){return {nodes:[],appendChild(node){content.nodes.shift();this.nodes.push(node)}}}};
let cloudCurrentPage='quotes',currentPageForData='quotes';
const ctx=vm.createContext({document,user:{uid:'admin-1'},cloudCurrentPage,currentPageForData,renderGlobalProjectSelector(){},originalGo(page){ctx.cloudCurrentPage=page;content.nodes=[{editing:false,page}]},go:null});
vm.runInContext(code.slice(start,end),ctx);
const quoteNode={editing:true,amount:{value:'95000000'},onSave(){return 'saved'}};
content.nodes=[quoteNode];
vm.runInContext("go('clients')",ctx);
assert.equal(content.nodes[0].page,'clients');
const clientNode={editing:true,contact:{value:'Mme Aina'}};
content.nodes=[clientNode];
vm.runInContext("go('quotes')",ctx);
assert.strictEqual(content.nodes[0],quoteNode);
assert.equal(content.nodes[0].amount.value,'95000000');
assert.equal(content.nodes[0].onSave(),'saved');
vm.runInContext("go('clients')",ctx);
assert.strictEqual(content.nodes[0],clientNode);
assert.equal(content.nodes[0].contact.value,'Mme Aina');
assert.match(code,/clients:\["Nom \/ raison sociale","Téléphone","Adresse","Personne de contact","E-mail","Chantier indicatif \(modifiable\)"\]/);
assert.match(code,/page==="clients"\?"Validé":f\.get\("workflow"\)/);
console.log('PASS: brouillons conservés dans chaque module, champs client séparés des montants.');
